### ISSUE TITLE
Bug: Sign In Button broken after clicking Landit Logo to go back to homepage

### ISSUE THREAD

**Issue by Leundai** [shaaddev/ApplicationRecord#20]
### Video
https://github.com/user-attachments/assets/ff55d020-38f6-4aed-99f2-e976e468410d

### Steps to reproduce:
- Click on logo
- Click on sign-in and get a white screen

### Other comments
- Cannot scroll after clicking back from the sign-up page
- Buttons are broken too after click back from the kinde login page

**Comment by Leundai** [comment]
Btw the white flashing when refreshing the page is very jarring, especially as a main dark-mode user.

**Comment by rukaiah-edhah** [comment]
Fixed the issue :)
